# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
